### PR TITLE
Fixed incorrect image relative linking.

### PR DESCRIPTION
**Pull request by yackermann**

### CODE REVIEW

**Comment by yackermann** [comment]
P.S. You should probably add https://ddbullfrog.github.io/iCard-Resume to the url of the repo *)

**Comment by yackermann** [comment]
Wow. Apparently it is related to #4 *)

**Comment by ddbullfrog** [comment]
Thanks for your fix.

**Comment by yackermann** [comment]
@ddbullfrog Thank you for theme *)

**Pull request merged**
